export const COMICS = [
  {
    id: "CV-001",
    title: "Void Rift: Nexus Rising",
    publisher: "Astral Forge",
    description:
      "Dimension-surfing tactician Cassia Voss leads a strike team through unstable portals to keep an ancient AI from rewriting reality.",
    characters: ["Cassia Voss", "Drake Kade"],
    genre: ["Sci-Fi", "Action"],
    price: 4.99,
    releaseDate: "2025-08-15",
    coverImg: "/covers/void-rift.svg",
    isNew: true,
    isPopular: true,
    featuredHeroRank: 1,
  },
  {
    id: "CV-002",
    title: "Mythic Dawn Protocol",
    publisher: "Titan Quill",
    description:
      "A rogue archivist unseals forgotten pantheon weapons, igniting a race between gods, heroes, and corporations across Neo-Delphi.",
    characters: ["Elara Vane"],
    genre: ["Fantasy", "Thriller"],
    price: 5.49,
    releaseDate: "2025-05-01",
    coverImg: "/covers/mythic-dawn.svg",
    isNew: true,
    isPopular: false,
    featuredHeroRank: 2,
  },
  {
    id: "CV-003",
    title: "Quantum Guardian: Parallax",
    publisher: "Nova Gate",
    description:
      "Time-looped hero Ishan Reyes must recruit his past selves to stop a chronophage feeding on paradoxes.",
    characters: ["Ishan Reyes"],
    genre: ["Sci-Fi", "Superhero"],
    price: 3.99,
    releaseDate: "2024-11-10",
    coverImg: "/covers/quantum-guardian.svg",
    isNew: false,
    isPopular: true,
    featuredHeroRank: 3,
  },
  {
    id: "CV-004",
    title: "Lunar Legion: Eventide",
    publisher: "Astral Forge",
    description:
      "The Lunar Legion uncovers a conspiracy tying the first moon colony to a sentient tide controlling Earth's oceans.",
    characters: ["Commander Nyx", "Kaito Ryu"],
    genre: ["Sci-Fi", "Drama"],
    price: 4.49,
    releaseDate: "2024-07-22",
    coverImg: "/covers/lunar-legion.svg",
    isNew: false,
    isPopular: true,
  },
  {
    id: "CV-005",
    title: "Chrome Samurai: Neon Oath",
    publisher: "Ion Ink",
    description:
      "Cybernetic swordswoman Aiko must defend Neo-Osaka's soul district from memory brokers siphoning emotions.",
    characters: ["Aiko", "Professor Mori"],
    genre: ["Cyberpunk", "Action"],
    price: 5.99,
    releaseDate: "2025-01-18",
    coverImg: "/covers/chrome-samurai.svg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "CV-006",
    title: "Storm Sigil",
    publisher: "Myriad Press",
    description:
      "A weather witch bound to a pirate crew must choose between controlling the storms or freeing the seas.",
    characters: ["Seren Gale"],
    genre: ["Fantasy", "Adventure"],
    price: 3.49,
    releaseDate: "2023-10-05",
    coverImg: "/covers/storm-sigil.svg",
    isNew: false,
    isPopular: false,
  },
  {
    id: "CV-007",
    title: "Arc Reactor Kids",
    publisher: "Nova Gate",
    description:
      "Genius misfit teens reverse-engineer alien biotech to form the most chaotic junior hero squad on Earth.",
    characters: ["Juno", "Lo"],
    genre: ["All Ages", "Superhero"],
    price: 2.99,
    releaseDate: "2024-04-28",
    coverImg: "/covers/arc-reactor.svg",
    isNew: false,
    isPopular: true,
  },
  {
    id: "CV-008",
    title: "Citadel Noir",
    publisher: "Titan Quill",
    description:
      "A detective cursed to relive the same night hunts a shapeshifter through the neon undercities of Vega Prime.",
    characters: ["Detective Vale"],
    genre: ["Noir", "Sci-Fi"],
    price: 4.29,
    releaseDate: "2024-02-14",
    coverImg: "/covers/citadel-noir.svg",
    isNew: false,
    isPopular: false,
  },
  {
    id: "CV-009",
    title: "Verdant Requiem",
    publisher: "Greenlight",
    description:
      "Nature spirits stage a symphonic rebellion against megacities, and one botanist can decode their music.",
    characters: ["Dr. Mira Ansel"],
    genre: ["Eco", "Fantasy"],
    price: 3.79,
    releaseDate: "2023-12-03",
    coverImg: "/covers/verdant-requiem.svg",
    isNew: false,
    isPopular: false,
  },
  {
    id: "CV-010",
    title: "Pulsebreakers",
    publisher: "Ion Ink",
    description:
      "An underground racing crew hacks gravity wells to deliver banned medicine across orbiting cities.",
    characters: ["Mara Flux", "Echo"],
    genre: ["Action", "Sci-Fi"],
    price: 4.79,
    releaseDate: "2024-09-09",
    coverImg: "/covers/pulsebreakers.svg",
    isNew: false,
    isPopular: true,
  },
  {
    id: "CV-011",
    title: "Crown of Static",
    publisher: "Myriad Press",
    description:
      "When broadcast towers awaken as titans, a street DJ weaponizes sound to keep the peace.",
    characters: ["DJ Lumen"],
    genre: ["Urban", "Fantasy"],
    price: 3.29,
    releaseDate: "2023-09-12",
    coverImg: "/covers/crown-of-static.svg",
    isNew: false,
    isPopular: false,
  },
  {
    id: "CV-012",
    title: "Atlas Division: Redshift",
    publisher: "Astral Forge",
    description:
      "Earth's premier defense unit confronts a star eater that feeds on courage, forcing heroes to share fears.",
    characters: ["General Mara", "Atlas Squad"],
    genre: ["Superhero", "Drama"],
    price: 5.29,
    releaseDate: "2025-03-19",
    coverImg: "/covers/atlas-division.svg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "MV-001",
    title: "The Amazing Spider-Man: Web of Shadows",
    publisher: "Marvel",
    description:
      "Peter Parker faces his greatest challenge when a symbiote invasion threatens New York City and he must choose between power and responsibility.",
    characters: ["Spider-Man", "Venom", "Black Cat"],
    genre: ["Superhero", "Action"],
    price: 4.99,
    releaseDate: "2025-06-01",
    coverImg: "/spider-man-swinging-through-new-york-city-at-night.jpg",
    isNew: true,
    isPopular: true,
    featuredHeroRank: 4,
  },
  {
    id: "MV-002",
    title: "Avengers: Infinity Protocol",
    publisher: "Marvel",
    description:
      "The Avengers must reunite to stop a cosmic threat that spans multiple timelines, testing their bonds like never before.",
    characters: ["Iron Man", "Captain America", "Thor", "Black Widow"],
    genre: ["Superhero", "Action"],
    price: 5.99,
    releaseDate: "2025-07-15",
    coverImg: "/avengers-team-assembled-in-heroic-pose-with-cosmic.jpg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "MV-003",
    title: "X-Men: Days of Future Past",
    publisher: "Marvel",
    description:
      "In a dystopian future, the X-Men must send Wolverine back in time to prevent the event that leads to their doom.",
    characters: ["Wolverine", "Professor X", "Magneto", "Storm"],
    genre: ["Superhero", "Sci-Fi"],
    price: 4.49,
    releaseDate: "2024-10-22",
    coverImg: "/x-men-team-in-futuristic-dystopian-setting-with-se.jpg",
    isNew: false,
    isPopular: true,
  },
  {
    id: "MV-004",
    title: "Black Panther: Wakanda Forever",
    publisher: "Marvel",
    description:
      "T'Challa protects Wakanda from invaders seeking to exploit its vibranium resources while honoring his ancestors' legacy.",
    characters: ["Black Panther", "Shuri", "Okoye"],
    genre: ["Superhero", "Action"],
    price: 5.49,
    releaseDate: "2025-04-10",
    coverImg: "/black-panther-in-wakandan-royal-suit-with-advanced.jpg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "MV-005",
    title: "Doctor Strange: Multiverse of Madness",
    publisher: "Marvel",
    description:
      "The Sorcerer Supreme navigates dangerous dimensions to stop an entity threatening to collapse all realities into one.",
    characters: ["Doctor Strange", "Wong", "Scarlet Witch"],
    genre: ["Superhero", "Fantasy"],
    price: 4.99,
    releaseDate: "2024-12-05",
    coverImg: "/doctor-strange-casting-mystical-spells-with-multiv.jpg",
    isNew: false,
    isPopular: true,
  },
  {
    id: "MV-006",
    title: "Deadpool: Maximum Effort",
    publisher: "Marvel",
    description:
      "Wade Wilson breaks the fourth wall and every rule in the book to save his friends from a time-traveling villain with a grudge.",
    characters: ["Deadpool", "Cable", "Domino"],
    genre: ["Superhero", "Comedy"],
    price: 3.99,
    releaseDate: "2025-02-14",
    coverImg: "/deadpool-in-action-pose-with-explosions-and-comedi.jpg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "DC-001",
    title: "Batman: The Dark Knight Returns",
    publisher: "DC Comics",
    description:
      "An aging Bruce Wayne emerges from retirement to save Gotham from a new wave of crime, facing both old enemies and the forces of government.",
    characters: ["Batman", "Robin", "The Joker"],
    genre: ["Superhero", "Noir"],
    price: 5.99,
    releaseDate: "2025-05-20",
    coverImg: "/batman-dark-silhouette-overlooking-gotham-city-at-.jpg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "DC-002",
    title: "Superman: Man of Tomorrow",
    publisher: "DC Comics",
    description:
      "Clark Kent confronts a threat from his Kryptonian past that forces him to choose between two worlds he calls home.",
    characters: ["Superman", "Lois Lane", "Lex Luthor"],
    genre: ["Superhero", "Action"],
    price: 4.99,
    releaseDate: "2025-06-30",
    coverImg: "/superman-flying-heroically-with-cape-flowing-and-s.jpg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "DC-003",
    title: "Wonder Woman: Gods and Mortals",
    publisher: "DC Comics",
    description:
      "Diana Prince must bridge the divide between the mortal world and Mount Olympus when ancient gods return to reclaim Earth.",
    characters: ["Wonder Woman", "Steve Trevor", "Ares"],
    genre: ["Superhero", "Fantasy"],
    price: 5.49,
    releaseDate: "2024-11-18",
    coverImg: "/wonder-woman-with-golden-lasso-and-shield-in-greek.jpg",
    isNew: false,
    isPopular: true,
  },
  {
    id: "DC-004",
    title: "The Flash: Speed Force Chronicles",
    publisher: "DC Comics",
    description:
      "Barry Allen races through time to prevent a catastrophic timeline collapse, but discovers his actions may be the cause.",
    characters: ["The Flash", "Kid Flash", "Reverse-Flash"],
    genre: ["Superhero", "Sci-Fi"],
    price: 4.49,
    releaseDate: "2024-09-25",
    coverImg: "/the-flash-running-with-lightning-trail-and-speed-f.jpg",
    isNew: false,
    isPopular: true,
  },
  {
    id: "DC-005",
    title: "Justice League: Crisis on Infinite Earths",
    publisher: "DC Comics",
    description:
      "The greatest heroes of multiple Earths unite to stop the Anti-Monitor from destroying the entire multiverse.",
    characters: ["Superman", "Batman", "Wonder Woman", "Flash", "Green Lantern"],
    genre: ["Superhero", "Action"],
    price: 6.49,
    releaseDate: "2025-08-10",
    coverImg: "/justice-league-heroes-assembled-with-multiverse-co.jpg",
    isNew: true,
    isPopular: true,
  },
  {
    id: "DC-006",
    title: "Aquaman: Depths of Atlantis",
    publisher: "DC Comics",
    description:
      "Arthur Curry must unite the seven underwater kingdoms to face an ancient evil rising from the deepest ocean trenches.",
    characters: ["Aquaman", "Mera", "Ocean Master"],
    genre: ["Superhero", "Adventure"],
    price: 4.99,
    releaseDate: "2025-03-22",
    coverImg: "/aquaman-underwater-with-trident-and-atlantean-arch.jpg",
    isNew: true,
    isPopular: false,
  },
  {
    id: "DC-007",
    title: "Green Lantern: Brightest Day",
    publisher: "DC Comics",
    description:
      "Hal Jordan and the Green Lantern Corps face their greatest test when the emotional spectrum itself begins to fracture.",
    characters: ["Green Lantern", "Sinestro", "Kilowog"],
    genre: ["Superhero", "Sci-Fi"],
    price: 4.79,
    releaseDate: "2024-08-15",
    coverImg: "/green-lantern-with-glowing-power-ring-creating-con.jpg",
    isNew: false,
    isPopular: true,
  },
];

export const getComicById = (id) => COMICS.find((comic) => comic.id === id);

export const listPublishers = () => [
  ...new Set(COMICS.map((comic) => comic.publisher)),
];

export const listGenres = () => [
  ...new Set(COMICS.flatMap((comic) => comic.genre)),
];

export const featuredComics = () =>
  COMICS.filter((comic) => comic.featuredHeroRank)
    .sort((a, b) => a.featuredHeroRank - b.featuredHeroRank)
    .slice(0, 3);

export const newReleaseComics = () => COMICS.filter((comic) => comic.isNew);

export const popularComics = () => COMICS.filter((comic) => comic.isPopular);
